### ISSUE TITLE
[BUG] Authentication error while logging in

### ISSUE THREAD

**Issue by piwonski** [tapglue/android_sdk#17]
When I call `Tapglue.user().createAndLoginUser()` method with `TGUser` provided, I receive an error. Android Logcat shows:
`D/OkHttp: {"errors":[{"code":4001,"message":"authentication error"}]}`
The call always fails.

**Comment by panzerdev** [comment]
The User which has problem is

username: u23157387
pasword: c83b05bd-cea8-40e9-8334-a5b875380c2e

The same user can login on iOs

**Comment by dlsniper** [comment]
@panzerdev please don't put such details here. There's a Slack channel we've created to handle these kind of issues / information. Thank you.
