### ISSUE TITLE
TGEvent Has Several Incorrect SerializedNames

### ISSUE THREAD

**Issue by thorbenprimke** [tapglue/android_sdk#2]
On `TGEvent` the location and priority fields have incorrect SerializedNames values. 

```
    @Expose
    @SerializedName("mLocation")
    private String mLocation;
    @Expose
    @SerializedName("mPriority")
    private String mPriority;
```

```
    @Expose
    @SerializedName("location")
    private String mLocation;
    @Expose
    @SerializedName("priority")
    private String mPriority;
```

I'm not sure if others need to be fixed as well. I only ran into the problem that the location was serialized incorrectly. 
I'm happy to put a PR out later.

**Comment by dlsniper** [comment]
@thorbenprimke this will be fixed in an upcoming PR. Thank you for reporting it.
