### ISSUE TITLE
Metadata should allow for more than just strings

### ISSUE THREAD

**Issue by dlsniper** [tapglue/android_sdk#20]
Metadata field should allow for any object to be passed to and from the API.
We should find a way to allow this to happen.

**Comment by AutomatedPlayground** [comment]
Strings can contain JSON data, therefore can be serialized/deserialized manually by end-programmers to any kind of object - even more than our Tapglue objects ;) This is my solution, but if you find any other we can try it.

**Comment by dlsniper** [comment]
I've created the following program and it seems to work ok:

```java
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.HashMap;

class Main {
    public static void main(String[] args) {
        case1();
        case2();
        case3();
    }

    private static void case1() {
        MyClassTwo y = new MyClassTwo();
        y.FieldIsh = "yey";

        MyClass cls = new MyClass();
        cls.Field = "Hello";
        cls.Field2 = y;

        String serializedObj = serializeToJson(cls);
        System.out.printf("ehlo: %s\n", serializedObj);

        MyClass x = deserializeFromJson(serializedObj);
        System.out.printf("aloha: %s\n", x.Field);
        System.out.printf("aloha: %s\n", x.Field2);

        if (x.Field2 instanceof MyClassTwo) {
            System.out.printf("yup\n");
        }
    }

    private static void case2() {

        MyClass cls = new MyClass();
        cls.Field = "Hello";
        cls.Field2 = "ehlo";

        String serializedObj = serializeToJson(cls);
        System.out.printf("ehlo: %s\n", serializedObj);

        MyClass x = deserializeFromJson(serializedObj);
        System.out.printf("aloha: %s\n", x.Field);
        System.out.printf("aloha: %s\n", x.Field2);

        if (x.Field2 instanceof String) {
            System.out.printf("yup\n");
        }
    }

    private static void case3() {
        HashMap<String, String> map = new HashMap<>(2);
        map.put("demo", "demo");
        map.put("demo2", "demo2");

        MyClass cls = new MyClass();
        cls.Field = "Hello";
        cls.Field2 = map;

        String serializedObj = serializeToJson(cls);
        System.out.printf("ehlo: %s\n", serializedObj);

        MyClass x = deserializeFromJson(serializedObj);
        System.out.printf("aloha: %s\n", x.Field);
        System.out.printf("aloha: %s\n", x.Field2);

        if (x.Field2 instanceof HashMap) {
            System.out.printf("yup\n");
        }
    }

    public static class MyClass {
        @Expose
        @SerializedName("field")
        String Field;

        @Expose
        @SerializedName("field2")
        Object Field2;
    }

    public static class MyClassTwo {
        @Expose
        @SerializedName("fieldIsh")
        String FieldIsh;
    }

    private static String serializeToJson(MyClass myClass) {
        Gson gson = new Gson();
        return gson.toJson(myClass);
    }

    private static MyClass deserializeFromJson(String jsonString) {
        Gson gson = new Gson();
        return gson.fromJson(jsonString, MyClass.class);
    }
}
```

As such, I'll propose to revert our metadata to have a type Object and allow the users to send anything they want there. We'll just have to ensure they know, from the documentation, that they have to send a type that's compatible with gson.

**Comment by AutomatedPlayground** [comment]
Sample code to show what's the problem:

SchemaClass<CustomClassA> myObject = new SchemaClass<>();
        SchemaClass<CustomClassB> myObject2 = new SchemaClass<>();
        myObject.field = new CustomClassA();
        myObject2.field = new CustomClassB();
        myObject.field.fieldA = 10;
        myObject2.field.fieldB = "testField";
        // we cant guess what class is used as "T" so we create saving and loading token with type of object
        Type type = new TypeToken<SchemaClass<Object>>() {
        }.getType();
        String jsonOfMyObject = new Gson().toJson(myObject, type);
        String jsonOfMyObject2 = new Gson().toJson(myObject2, type);
        // now deserialize it
        SchemaClass<Object> myObjectAfterDeserialization = new Gson().fromJson(jsonOfMyObject, type);
        SchemaClass<Object> myObject2AfterDeserialization = new Gson().fromJson(jsonOfMyObject2, type);
        assertEquals(myObject2.field.fieldB, ((CustomClassB) myObject2AfterDeserialization.field).fieldB);
        assertEquals(myObject.field.fieldA, ((CustomClassA) myObjectAfterDeserialization.field).fieldA);

GSON deserializes "field" as linkedMap, so to get fieldA we would need to do:
myObjectAfterDeserialization.field.get("fieldA") - if it would be a bigger object instead of primitive variable, we would receive another linkedMap with its parameters. So I think It's easier to access when we use it as string and then developers can parse it however they want
