### ISSUE TITLE
Export as jar not aar

### ISSUE THREAD

**Issue by panzerdev** [tapglue/android_sdk#28]
This lib get's exported as an aar instead of a jar withouth the need to do so.

**Comment by dlsniper** [comment]
Thank you for the suggestion however this won't be changed.

**Comment by panzerdev** [comment]
What is the reason for that?

**Comment by dlsniper** [comment]
Two reasons:
- there's no solid reason to make the change to `.jar` format
- there will be future changes which will require the `.aar` format
