### ISSUE TITLE
User social_ids should be a map<string,string> not Array<string>

### ISSUE THREAD

**Issue by dlsniper** [tapglue/android_sdk#9]
User social ids are a map between the social network and their ID on that network.
As such, the field should be changed from array<string> to map<string, string>
Thank you.

**Comment by AutomatedPlayground** [comment]
From slack:
onur 5:20 PM One more thing, social_platform should be a single string, not a list.

As I undestood this, on this network request I can sent multiple ids, but all for just one platform - therefore this code supports sending multiple ids that came from one platform. As you can see user can enter as many ids from multiple social platforms, but on translation for network requests if those are from different platforms it will cause UNSUPPORTED_INPUT error - TGNetworkManager, line 440.

Also - switching to MAP would drop support for multiple ids for one platform and enable "1 ID for each socialNetwork"

**Comment by AutomatedPlayground** [comment]
Regarding above - interface for end-developers changed to:

void searchUsersWithSocialUserIds(String socialPlatform,List<String> socialIds, TGRequestCallback<TGConnectionUsersList> output);

Inside library it would stay as it is, as data was meant to contain one social pair - "id and platform" - this won't block us in future extensions and don't harm anything in current code clearance or flow.

**Comment by dlsniper** [comment]
Fixed in #5
